// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gouvppphdylyelwhercx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdXZwcHBoZHlseWVsd2hlcmN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDc4MDIsImV4cCI6MjA1ODEyMzgwMn0.5qqiOZWOkO36esKI5E0CSqnfhZ2_taIs2JPZcuZuh-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);